import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import Script from "next/script";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="hunting coder,blog,nextjs" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload" /> */}

      <nav className={styles.mainnav}>
        <ul>
          <li>Home</li>
          <li>Blog</li>
          <li>About</li>
          <li>Contact</li>
        </ul>
      </nav>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <Link href="/">Hunting Coder!</Link>
        </h1>

        <p className={styles.description}>Hunting Developers Around World</p>

        <div className={styles.grid}>
          <div className="blogs">
            <h2>Popular Blogs</h2>
            <div className="blogItem">
              <h3>How To Learn JavaScript</h3>
              <p>JavaScript Is The Web Language.</p>
            </div>
            <div className="blogItem">
              <h3>How To Learn JavaScript</h3>
              <p>JavaScript Is The Web Language.</p>
            </div>
            <div className="blogItem">
              <h3>How To Learn JavaScript</h3>
              <p>JavaScript Is The Web Language.</p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
